services:
  - type: web
    name: luck
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -t 120 -b 0.0.0.0:$PORT app:app
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: uploads
      mountPath: /opt/render/project/src/static/uploads
      sizeGB: 1